/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import Interfaces.ILogica;
import static Interfaces.Implementacion.FabricaLogica.dameInstancia;
import ObjetoNegocio.Presencial;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jarol
 */
public class BuscarCasting extends javax.swing.JPanel {

       ILogica logica;
   
    /**
     * Creates new form BuscarCasting
     */
    public BuscarCasting() {
        initComponents();
        logica= dameInstancia();
    }

    
    public JPanel despliegaPanel()
    {
           this.setSize(1800, 700);// tamano del panel
        this.setLocation(5,5);// posicion dentro del panel principal
        System.out.println("hola");
       return this;
    }

            /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCastings = new javax.swing.JTable();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("Código:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel3.setText("Fecha contratación:");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));
        fondo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 160, -1));
        fondo.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 170, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        fondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        tblCastings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripción", "Fecha contratación", "Coste", "Tipo", "Cliente", "Agente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCastings);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 870, 270));
        fondo.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
           try {
               buscarCasting();
           } catch (ParseException ex) {
               Logger.getLogger(BuscarCasting.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_btnBuscarActionPerformed


     public void buscarCasting() throws ParseException
     {
         String nombre,codigo;
         Date fecha = null;
         
           //    String  fech = datePicker.getDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
       // SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
         
       // fecha=date.parse(fech);
         nombre= txtNombre.getText();
         codigo=txtCodigo.getText();
         try
         {
             
       llenarTabla( logica.consultarTodosCasting(nombre, codigo, fecha));
         }catch(RuntimeException ex)
         {
             mostrarError(ex);
         }
     }
     
     public void mostrarError(RuntimeException ex)
     {
        JOptionPane.showMessageDialog(this, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
     }
     
     
     public void llenarTabla(List<Presencial> list) throws ParseException
     {
        
        DefaultTableModel model= (DefaultTableModel) tblCastings.getModel();
 
        int rowCount = model.getRowCount();
        
        for(int m=rowCount-1;m>=0;m--)
        {
           model.removeRow(m);
        }
        
        Object rowData[]=new Object[8];
        for(int i=0; i<list.size();i++){
            rowData[0]=list.get(i).getId();
            rowData[1]=list.get(i).getNombre();
            rowData[2]=list.get(i).getDescripcion();
            rowData[3]=list.get(i).getFecha_contratacion();
             rowData[4]=list.get(i).getCoste();
              rowData[5]=list.get(i).getTipo();
               rowData[6]=list.get(i).getCliente();
                  rowData[7]=list.get(i).getAgente();
            model.addRow(rowData);
        }
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCastings;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
