/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import static presentacion.FrmPrincipal.panelPrincipal;

/**
 *
 * @author Jarol
 */
public class PanelTablaCasting extends javax.swing.JPanel {

    
    PanelPerfil perfil= new PanelPerfil();
    /**
     * Creates new form TablaCastings
     */
    public PanelTablaCasting() {
        initComponents();
    }
    
public JPanel desplegarPanel()
{
     
        
        this.setSize(1090, 590);// tamano del panel
        this.setLocation(5,5);// posicion dentro del panel principal
        
return this;
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCastings = new javax.swing.JTable();
        btnRegistrarPerfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCastings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripción", "Fecha contratación", "Coste", "Tipo casting", " Numero personas", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCastings);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 830, 320));

        btnRegistrarPerfil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarPerfil.setText("Registrar Perfil");
        btnRegistrarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPerfilActionPerformed(evt);
            }
        });
        fondo.add(btnRegistrarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 140, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Castings");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPerfilActionPerformed
        //  aqui falta la condicion para ver si se selecciono un casting

        perfil.desplegarPanel();
    }//GEN-LAST:event_btnRegistrarPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPerfil;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCastings;
    // End of variables declaration//GEN-END:variables
}
