/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import ObjetoNegocio.Agente;
import org.bson.types.ObjectId;
import Control.CtrAgente;
import Interfaces.ILogica;
import static Interfaces.Implementacion.FabricaLogica.dameInstancia;
import ObjetoNegocio.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian Daniel Acedo Chaidez // ID: 00000228373
 */
public class PanelAgenteCasting extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgenteCasting
     */
    ILogica logica;

    public PanelAgenteCasting() {
        initComponents();
        logica = dameInstancia();
        llenarTabla();
    }
     
    public JPanel despliegaPanel()
    {
           this.setSize(1800, 700);// tamano del panel
        this.setLocation(5,5);// posicion dentro del panel principal
        
       return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        txtCURP = new javax.swing.JTextField();
        Scroll = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, -1));
        fondo.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 200, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        fondo.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        fondo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel3.setText("Nombre:");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setText("Dirección:");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setText("CURP:");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel6.setText("RFC:");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        fondo.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, -1));
        fondo.add(txtCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Dirección", "CURP", "RFC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Scroll.setViewportView(tblClientes);

        fondo.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 590, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
             String Nombre = txtNombre.getText();
        String Direccion = txtDireccion.getText();
        String CURP = txtCURP.getText();
        String RFC = txtRFC.getText();

        Agente agente = new Agente(RFC, CURP, Nombre, Direccion, new ObjectId());

        try {
            agente.validarDatos(agente);
            logica.registrarAgente(agente);
            limpiarCampos();
            llenarTabla();

            mostrarMensajeExito(agente);

        } catch (RuntimeException ex) {
            mostrarError(ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public void limpiarCampos() {
        txtNombre.setText("");
        txtDireccion.setText("");
        txtCURP.setText("");
        txtRFC.setText("");
    }

    public void mostrarError(Exception ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Muestra mensaje de exito y busca el cliente para obtener el id con el que
     * se registro para mostrarlo en el mensaje
     *
     * @param cliente
     */
    private void mostrarMensajeExito(Agente agente) {
      JOptionPane.showMessageDialog(null, "Se creo el agente con exito"); //To change body of generated methods, choose Tools | Templates.
    }

    public void llenarTabla() {
        List<Agente> list = logica.consultarTodosAgentes();
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();

        int rowCount = model.getRowCount();

        for (int m = rowCount - 1; m >= 0; m--) {
            model.removeRow(m);
        }

        Object rowData[] = new Object[5];
            
        
        for (int i = 0; i < list.size(); i++) {
            
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getNombre();
            rowData[2] = list.get(i).getDireccion();
            rowData[3] = list.get(i).getCURP();
            rowData[4] = list.get(i).getRFC();
            model.addRow(rowData);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables

}
