/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import static presentacion.FrmPrincipal.panelPrincipal;

/**
 *
 * @author Jarol
 */
public class PanelPerfil extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarPerfil
     */
    public PanelPerfil() {
        initComponents();
 
     
    }
    
    
    public void desplegarPanel()
    {
        recuperarDatos();
        this.setSize(1090, 590);// tamano del panel
        this.setLocation(5,5);// posicion dentro del panel principal
     
        panelPrincipal.removeAll();
        panelPrincipal.add(this,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
  
    }
    
 
    public void recuperarDatos()
    {
           
       
    }
    
    public void limpiarCampos(){
        txtNombreCliente.setText("");
        txtNombreAgente.setText("");
        txtId.setText("");
        txtSexo.setText("");
        txtColorPelo.setText("");
        txtColorOjos.setText("");
        txtExperiencia.setText("");
        txtTipoCasting.setText("");
        grupoEspecialidad.clearSelection();
        comboBoxEstado.setSelectedIndex(0);
        comboBoxEdad.setSelectedIndex(0);
        comboBoxAltura.setSelectedIndex(0);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEspecialidad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtColorOjos = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtColorPelo = new javax.swing.JTextField();
        txtExperiencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboBoxEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboBoxEdad = new javax.swing.JComboBox<>();
        comboBoxAltura = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerfiles = new javax.swing.JTable();
        btnRegistrarPerfil = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        especialidadModelo = new javax.swing.JRadioButton();
        especialidadActor = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtNombreAgente = new javax.swing.JTextField();
        txtTipoCasting = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Sexo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel4.setText("Color pelo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setText("Color ojos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setText("Experiencia:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 190, -1));
        jPanel1.add(txtColorOjos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 190, -1));
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, -1));
        jPanel1.add(txtColorPelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, -1));
        jPanel1.add(txtExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 190, -1));

        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel8.setText("Especialidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel9.setText("Rango edad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel10.setText("Rango altura:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        comboBoxEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        comboBoxAltura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        tblPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sexo", "Color pelo", "Color Ojos", "Experiencia", "Estado", "Especialidad", "Rango edad", "Rango altura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerfiles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 710, 190));

        btnRegistrarPerfil.setText("Registrar");
        jPanel1.add(btnRegistrarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        grupoEspecialidad.add(especialidadModelo);
        especialidadModelo.setText("Modelo");
        jPanel1.add(especialidadModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        grupoEspecialidad.add(especialidadActor);
        especialidadActor.setText("Actor");
        jPanel1.add(especialidadActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Perfiles");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Datos Casting seleccionado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        jLabel13.setText("Nombre cliente:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel14.setText("Nombre agente:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        jLabel15.setText("TipoCasting");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 70, 20));
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 210, -1));
        jPanel1.add(txtNombreAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 210, -1));
        jPanel1.add(txtTipoCasting, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarPerfil;
    private javax.swing.JComboBox<String> comboBoxAltura;
    private javax.swing.JComboBox<String> comboBoxEdad;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JRadioButton especialidadActor;
    private javax.swing.JRadioButton especialidadModelo;
    private javax.swing.ButtonGroup grupoEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerfiles;
    private javax.swing.JTextField txtColorOjos;
    private javax.swing.JTextField txtColorPelo;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreAgente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTipoCasting;
    // End of variables declaration//GEN-END:variables
}
